apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup-cronjob
spec:
  schedule: '0 0 * * *'
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60 # delete job after 60 seconds
      template:
        spec:
          containers:
            - name: mongodb-backup
              image: your-docker-repo/backup-to-excel:latest
              env:
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      key: uri
                      name: mongodb-secret
                - name: OUTPUT_DIR
                  value: '/mnt/host/mongo-backups'
              volumeMounts:
                - mountPath: '/mnt/host/mongo-backups'
                  name: host-volume
          volumes:
            - name: host-volume
              hostPath:
                path: /mnt/c/mongo-backups # This path depends on your local setup (for Minikube or Docker Desktop)
                type: Directory
          restartPolicy: Never
